### ISSUE TITLE
need caldata

### ISSUE THREAD

**Issue by youxiaojie** [psyborg55/tp-link#1]
dear friend, I hope to test it with pc, so I need an art data for caldata. if you have art or caldata, could you share with me? yxj790222@163.com, thanks!

**Comment by psyborg55** [comment]
nope, i only made firmware. at the time it was done (k4.14) it was enough to boot card on both router and laptop

**Comment by youxiaojie** [comment]
really? that is great. I try 9984 on pc, it need not only firmware but also caldata to use the card. by using firmware, will I patch and compile ath10k driver ?

**Comment by psyborg55** [comment]
hard to tell. i have only 9880 v1 and v2. 9984 could be different

**Comment by youxiaojie** [comment]
by using firmware, will I patch and compile ath10k driver ?

**Comment by psyborg55** [comment]
yes, if u apply driver patch as well
